### ISSUE TITLE
Print styles: remove metadata

### ISSUE THREAD

**Issue by pollardld** [MidAtlanticPortal/mp-visualize#10]
- [x] remove the metadata from the map
  - [x] the sourcing should include the sources for the basemap layers
     *as in the NE ODP export in the bottom right-hand corner below the scale bar (i.e. ESRI, DeLorme, GEBCO, NGDC....)*

Extended metadata are not needed for the export

**Question**
Is meta data on printed map required?

**Comment by rhodges** [comment]
Metadata is not included along with the map by default.
