### ISSUE TITLE
Address toggleActive() and showSublayers() functionality

### ISSUE THREAD

**Issue by dnseminara** [MidAtlanticPortal/mp-visualize#4]
The crux of these CAS issues sort've percolate from having an additional, third tier of functionality.  This ticket is more of an overarching notification, rather than an actual implementation of a suggestive fix.

**Some starting points are here:** 
- showSublayers() either needs to be added to sub-sublayers (ports) or account for that use case everytime that appears
  
  ``` javascript
  //models.js:608
  
  self.showSublayers = ko.observable(false);
  ```
- This fires every time a mouse click happens on the body - but currently, there's no subLayer of a sub-sublayer and produces an error.
  
  ``` javascript
  //app.js:189
  
  $(document).on('click', 'body', function(event) {
      var activeLayer = app.viewModel.activeLayer();
      var elm = '.layer.open.dropdown';
      if (activeLayer && (activeLayer.showSublayers() || $(elm).length)) {
        app.viewModel.outsideSubLayer(event, elm);
      }
    });
  ```
- Activation of port layers produces weird results with the activeLayer logic and is part of the reason that deactivation of these layers don't work. If a single CAS port has been activated, you'll see that you can't delete them. During the next go around, add two ports and put a debugger within toggleActive ~794.  You'll see that activeLayer doesn't behave the same way for both CAS port layers. This may be helpful for ticket #3 
  
  ``` javascript
  //models.js:794 - in self.toggleActive()
  
  if (layer !== activeLayer && typeof activeLayer !== 'undefined') {
          // are these CAS/VTR layers?
  ```

**Comment by pollardld** [comment]
added to model.js

```
line:794   typeof activeLayer.parentDirectory == 'Function'

line:801   typeof activeLayer.parentDirectory == 'Function'
```

added to app.js  

```
line: 189   if (activeLayer && typeof activeLayer.showSublayers == 'function')
```

To fix errors. will push with other issue fixes
