### ISSUE TITLE
Active Tab (i)con should show Gear/Date Range

### ISSUE THREAD

**Issue by dnseminara** [MidAtlanticPortal/mp-visualize#7]
For port layers, the _Active Tab_ (i)con should display where it came from - since multiple port layers of the same name can be activated.  Functionality currently exists for MDAT query-able layers.

**Comment by pollardld** [comment]
https://github.com/MidAtlanticPortal/mp-visualize/blob/cas/visualize/templates/visualize/includes/layer-row.html examples of how mdat shows info on hover in active tab.  Add additional conditionals for vtr.

<img width="100%" alt="screen shot 2016-10-04 at 2 01 31 pm" src="https://cloud.githubusercontent.com/assets/2632164/19092353/1be11a5e-8a3b-11e6-9b83-f22e1dcf0177.png">

**Comment by pollardld** [comment]
fixed on sandbox. will push live with other issue updates.
