### ISSUE TITLE
Print Styling: Vector Styling is not maintained and does not match legend

### ISSUE THREAD

**Issue by rhodges** [MidAtlanticPortal/mp-visualize#9]
For example, the layers from the landing ocean story:
http://portal.midatlanticocean.org/visualize/#x=-76.04&y=37.75&z=9&logo=true&controls=true&dls%5B%5D=true&dls%5B%5D=1&dls%5B%5D=20&dls%5B%5D=true&dls%5B%5D=0.98&dls%5B%5D=59&dls%5B%5D=true&dls%5B%5D=0.5&dls%5B%5D=285&dls%5B%5D=false&dls%5B%5D=0.5&dls%5B%5D=89&basemap=Open+Street+Map&themes%5Bids%5D%5B%5D=5&tab=data&legends=false&layers=true

Look at Artificial Reefs layer - on portal and legend, outline is blue. On print it's thick and bright yellow.

**Comment by rhodges** [comment]
Here is the document I made for useing HTML2Canvas to generate image files. 
https://docs.google.com/document/d/1py1H9XK9SZk-i3DMM56WxdACi1UUBlEdru_UpX2kvfE/edit?usp=sharing

It's not great and still has some big open questions. I really hope the existing OL2 experimental project works:  http://dev.openlayers.org/sandbox/camptocamp/canvas/openlayers/examples/exportMapCanvas.html

**Comment by pollardld** [comment]
Vector style matching was caused by a line of css that was part of landmapper and accidentally got copied to marco.

Line of CSS is removed. Styles now match.
